# Generated by Django 3.1.1 on 2021-07-13 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 10, 3, 35, 483283, tzinfo=utc)),
        ),
    ]
